Repository CityOfZion/neo-local, pull requests merged in 2018-10, with the labels that each got.

#63 Update neo-python to v0.8.0
  VERSION
  cli/services/docker.go
  docker-compose.yml
Labels: Bug, Task

#62 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  VERSION
Labels: Documentation

#67 Update neo python to v0.8.1
  VERSION
  cli/services/docker.go
  docker-compose.yml
Labels: Task

#65 Update README version badge to point to releases
  README.md
  VERSION
Labels: Documentation

#68 Start Postgres container using CLI
  VERSION
  cli/commands/start.go
  cli/stack/postgres.go
  cli/stack/service.go
Labels: Feature

#82 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation, Task

#83 Add Code Owners
  .github/CODEOWNERS
Labels: Documentation, Task

#84 Update Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation, Task

#86 Status Command
  cli/commands/index.go
  cli/commands/status.go
  cli/main.go
  cli/services/docker.go
Labels: Feature

#96 Release v0.11.0
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  VERSION
  cli/commands/index.go
  cli/commands/status.go
  cli/main.go
  cli/services/docker.go
  scripts/travis.sh
Labels: Release
