Repository CityOfZion/neo-local, pull requests merged in 2018-11, with the labels that each got.

#103 Hotfix Release - 0.11.1
  VERSION
  cli/services/docker.go
  docker-compose.yml
  scripts/travis.sh
Labels: Release

#102 Down CLI command
  cli/commands/down.go
  cli/commands/index.go
  cli/commands/status.go
  cli/services/docker.go
  cli/stack/service.go
  cli/stack/services.go
Labels: Feature

#104 Add PrivateNet container to CLI
  cli/stack/privatenet.go
  cli/stack/services.go
Labels: Feature

#92 Finished 4 isolated consensus nodes
  .env
  .github/CODEOWNERS
  Makefile
  cli/services/docker.go
  cli/stack/postgres.go
  docker-compose.yml
  documentation/README.md
  documentation/assets/neo-local_ecosystem.jpg
  notifications-server.config.json
  privnet/Dockerfile
  privnet/change_neo-cli_node_version.sh
  privnet/configs/v2.7.6.1/config-windows.json
  privnet/configs/v2.7.6.1/config1.json
  privnet/configs/v2.7.6.1/config2.json
  privnet/configs/v2.7.6.1/config3.json
  privnet/configs/v2.7.6.1/config4.json
  privnet/configs/v2.7.6.1/protocol.json
  privnet/configs/v2.8.0/config-windows.json
  privnet/configs/v2.8.0/config1.json
  privnet/configs/v2.8.0/config2.json
  privnet/configs/v2.8.0/config3.json
  privnet/configs/v2.8.0/config4.json
  privnet/configs/v2.8.0/protocol.json
  privnet/configs/v2.9.0/config-windows.json
  privnet/configs/v2.9.0/config1.json
  privnet/configs/v2.9.0/config2.json
  privnet/configs/v2.9.0/config3.json
  privnet/configs/v2.9.0/config4.json
  privnet/configs/v2.9.0/protocol.json
  privnet/docker_wait_and_commit.sh
  privnet/scripts/claim_gas_fixedwallet.py
  privnet/scripts/claim_neo_and_gas.py
  privnet/scripts/claim_neo_and_gas_fixedwallet.py
  privnet/scripts/run.sh
  privnet/scripts/start_consensus_node.sh
  privnet/wallets/neo-privnet.python-wallet
  privnet/wallets/wallet1.json
  privnet/wallets/wallet2.json
  privnet/wallets/wallet3.json
  privnet/wallets/wallet4.json
  privnet/watch_nodes_sync.sh
  scripts/status.sh
Labels: Feature

#111 ContainerName cannot be based on ImageName
  cli/commands/start.go
  cli/commands/status.go
  cli/stack/faucet.go
  cli/stack/postgres.go
  cli/stack/service.go
Labels: Bug

#114 CLI: fix image pulling
  cli/services/docker.go
Labels: Bug

#109 Add neo-python to CLI
  cli/commands/start.go
  cli/commands/status.go
  cli/services/docker.go
  cli/stack/faucet.go
  cli/stack/neopython.go
  cli/stack/services.go
Labels: Feature

#115 Bootstrap Chain
  .env
  docker-compose.yml
  documentation/README.md
Labels: Feature
