Repository CityOfZion/neo-local, pull requests merged in 2018-12, with the labels that each got.

#124 Create cross platform Home dir and config file
  cli/config/config.go
Labels: Task

#136 Same neo-python versions and add missing service names
  cli/stack/neo_python.go
  cli/stack/notifications_server.go
  cli/stack/privatenet.go
  cli/stack/services.go
  docker-compose.yml
Labels: Bug

#135 Stop Command
  cli/Gopkg.lock
  cli/commands/index.go
  cli/commands/stop.go
Labels: Feature

#130 Hotfix Release - Autoheal healthcheck neo-scan-api
  VERSION
  docker-compose.yml
  scripts/ping.sh
  scripts/status.sh
Labels: Feature
